name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push all images
      uses: docker/build-push-action@v5
      with:
        contexts: |
          ./backend
          ./frontend
          ./infra
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/foodgram-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/foodgram-frontend:latest
          ${{ secrets.DOCKER_USERNAME }}/foodgram-nginx:latest

    - name: Send Telegram notification
      run: |
        curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Сборка контейнеров завершена успешно!"